### ISSUE TITLE
Got "global.serverConnector.addresses is empty" even if cfg.GetGlobal().GetServerConnector().SetAddresses called

### ISSUE THREAD

**Issue by Andrew-M-C** [trpc-ecosystem/go-naming-polarismesh#14]
### What version of trpc-go-naming-polarismesh are you using?

v1.0.0

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (go env)?

```
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/root/go/bin"
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY="github.com,gitlab.com,git.tencent.com"
GONOSUMDB="github.com,gitlab.com,git.tencent.com"
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE="github.com,gitlab.com,git.tencent.com"
GOPROXY="https://goproxy.io"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/projects/github.com/amcrpc/demo-go/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build475901713=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

My `trpc_go.yaml`:

```yaml
# blahblah
  registry:
    polarismesh:
      register_self: true
      heartbeat_interval: 3000
      protocol: grpc
      address_list: host.docker.internal:8090 # This is a local polaris docker container
      service:
        - name: trpc.study.HelloWorld
          namespace: dev
          bind_address: host.docker.internal:8000
          weight: 100
  selector:
    polarismesh:
      protocol: grpc
```

My `main.go`:

```go
package main

import (
	"os"

	"github.com/amcrpc/demo-go/trpc/client"
	"github.com/amcrpc/demo-go/trpc/service/helloworld"
	"github.com/polarismesh/polaris-go/api"
	trpc "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/log"

	_ "trpc.group/trpc-go/trpc-naming-polarismesh"
)

func main() {
	log.Infof("进入应用程序 %s", os.Args[0])
	server := trpc.NewServer()
	log.Info("初始化 trpc server 成功")

	helloworld.RegisterHelloWorldService(server)

	log.Info("启动服务")
	if err := server.Serve(); err != nil {
		log.Fatalf("服务运行失败: %v", err)
	}

	log.Warn("服务结束")
}
```

### What did you expect to see?

The log '启动服务' should appear and trpc service start serving. Also, the server should be registered in polaris system.

### What did you see instead?

```
2023-11-21 08:50:58.083 INFO    demo/demo_main.go:18    进入应用程序 ./trpc.study
panic: setup plugin fail: setup plugin selector-polarismesh error: new sdk ctx err: Polaris-1002(ErrCodeAPIInvalidConfig): fail to verify input config, cause: 1 error occurred:
        * global.serverConnector.addresses is empty



goroutine 1 [running]:
trpc.group/trpc-go/trpc-go.NewServer({0x0, 0x0, 0x0})
        /root/go/pkg/mod/trpc.group/trpc-go/trpc-go@v1.0.1/trpc.go:48 +0x1bb
main.main()
       /blahblah/demo_main.go:24 +0x131
```

**Comment by tocrafty** [comment]
opensource polarismesh does not support join_point(such as ChinaMainland or Sigpore, default as ChinaMainland), which is used internally by Tencent. 
You should config [`yaml.plugins.selector.polarismesh.address_list`](https://github.com/trpc-ecosystem/go-naming-polarismesh/blob/be8b817ada46055baf26e2ce736814ad122f37d8/README.md?plain=1#L163) explicitly with your private polaris server adresses.
Note that for historical reasons, registry and selector does not shares the same config and there are actually two polarismesh SDK both connecting to the same polaris server. Sad.

**Comment by Andrew-M-C** [comment]
@tocrafty I did configurred `yaml.plugins.selector.polarismesh.address_list` (may be for my faulty edit which made the content unreadable):

```yaml
# blahblah
  registry:
    polarismesh:
      register_self: true
      heartbeat_interval: 3000
      protocol: grpc
      address_list: host.docker.internal:8090 # This is a local polaris docker container
      service:
        - name: trpc.study.HelloWorld
          namespace: dev
          bind_address: host.docker.internal:8000
          weight: 100
  selector:
    polarismesh:
      protocol: grpc
```

However it did not work. Anything more should I configurred?

**Comment by tocrafty** [comment]
The yaml that you paste only configures `pugins.registry.polarismesh`，not `plugins.selector.polarismesh`.

**Comment by tocrafty** [comment]
```yaml
# blahblah
  registry:
    polarismesh:
      register_self: true
      heartbeat_interval: 3000
      protocol: grpc
      address_list: host.docker.internal:8090 # This is a local polaris docker container
      service:
        - name: trpc.study.HelloWorld
          namespace: dev
          bind_address: host.docker.internal:8000
          weight: 100
  selector:
    polarismesh:
      protocol: grpc
      address_list: host.docker.internal:8090 # copied from registry.polarismesh
```

**Comment by Andrew-M-C** [comment]
@tocrafty i see. i added `plugins.selector.polarismesh. address_list `, the error above disappear. but another error occurred:

```
2023-11-27 03:16:00.398 INFO    demo/demo_main.go:17    进入应用程序 ./trpc.study
2023-11-27 03:16:03.739 INFO    client/client_linux.go:35       client trpc.study.HelloWorld is empowered with tnet! 🤩 
2023-11-27 03:16:03.739 INFO    client/client_linux.go:35       client  is empowered with tnet! 🤩 
2023-11-27 03:16:03.749 DEBUG   maxprocs/maxprocs.go:47 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
2023-11-27 03:16:03.755 INFO    server/service_linux.go:21      service trpc.study.HelloWorld with network tcp and protocol trpc is empowered with tnet! 🤩 you can set 'transport: go-net' in your trpc_go.yaml's service configuration to switch to the golang net framework
2023-11-27 03:16:03.756 INFO    demo/demo_main.go:20    初始化 trpc server 成功
2023-11-27 03:16:03.756 INFO    demo/demo_main.go:31    启动服务
2023-11-27 03:16:03.756 INFO    tnet/server_transport.go:66     service:trpc.study.HelloWorld is using tnet transport, current number of pollers: 1
2023-11-27 03:16:03.757 ERROR   server/service.go:162   process:740, service:trpc.study.HelloWorld register fail:fail to Register instance, err is Polaris-1001(ErrCodeAPIInvalidArgument): fail to validate InstanceRegisterRequest: , cause: 1 error occurred:
        * InstanceRegisterRequest: host should not be empty


2023-11-27T03:16:03Z    INFO    tnet@v1.0.0/tcpservice.go:90    tnet tcp service started, current number of pollers: 1, use tnet.SetNumPollers to change it

2023-11-27 03:16:04.059 INFO    admin/admin.go:192      process:740, admin server, closed
2023-11-27 03:16:04.059 ERROR   server/serve_unix.go:82 service serve errors: 1 error occurred:
        * fail to Register instance, err is Polaris-1001(ErrCodeAPIInvalidArgument): fail to validate InstanceRegisterRequest: , cause: 1 error occurred:
        * InstanceRegisterRequest: host should not be empty




Note: it is normal to have "use of closed network connection" error during hot restart.
DO NOT panic.
2023-11-27 03:16:04.077 FATAL   demo/demo_main.go:33    服务运行失败: 1 error occurred:
        * fail to Register instance, err is Polaris-1001(ErrCodeAPIInvalidArgument): fail to validate InstanceRegisterRequest: , cause: 1 error occurred:
        * InstanceRegisterRequest: host should not be empty

```

full `trpc_go.yaml` file:

```yaml
server:
  filter:
    - tracelog
  service:
    - name: trpc.study.HelloWorld
      port: 8000
      network: tcp
      protocol: trpc
      timeout: 1800

plugins:
  log:
    default:
      - writer: console
        level: debug
        formatter: console  # 标准输出日志的格式
      - writer: file  # 本地文件日志
        level: debug  # 本地文件滚动日志的级别
        formatter: json  # 标准输出日志的格式
        formatter_config:
          time_fmt: 2006-01-02 15:04:05  # 日志时间格式。"2006-01-02 15:04:05"为常规时间格式，"seconds"为秒级时间戳，"milliseconds"为毫秒时间戳，"nanoseconds"为纳秒时间戳
          time_key: time  # 日志时间字段名称，不填默认"T"，填 "none" 可禁用此字段
          level_key: level  # 日志级别字段名称，不填默认"L"，填 "none" 可禁用此字段
          name_key: none  # 日志名称字段名称，不填默认"N"，填 "none" 可禁用此字段
          caller_key: caller  # 日志调用方字段名称，不填默认"C"，填 "none" 可禁用此字段
          message_key: message  # 日志消息体字段名称，不填默认"M"，填 "none" 可禁用此字段
          stacktrace_key: stack_trace  # 日志堆栈字段名称，不填默认"S"，填 "none" 可禁用此字段
        writer_config:
          log_path: ./log/
          filename: trpc.log  # 本地文件滚动日志存放的路径
          write_mode: 2  # 日志写入模式，1-同步，2-异步，3-极速 (异步丢弃), 不配置默认异步模式
          roll_type: size  # 文件滚动类型，time 为按时间滚动
          max_size: 1000 # MB
          max_backups: 10  # 最大日志文件数
  registry:
    polarismesh:
      register_self: true
      heartbeat_interval: 3000
      protocol: grpc
      address_list: host.docker.internal:8090
      service:
        - name: trpc.study.HelloWorld
          namespace: dev
          bind_address: host.docker.internal:8000
          weight: 100
          # token: nu/0WRA4EqSR1FagrjRj0fZwPXuGlMpX+zCuWu4uMqy8xr1vRjisSbA25aAC3mtU8MeeRsKhQiDAynUR09I=
          token: 7f6223bc3ba341d58b16db9762253a3b
  selector:
    polarismesh:
      protocol: grpc
      address_list: host.docker.internal:8090

client:
  filter:
    - tracelog
  service:
    - name: trpc.study.HelloWorld
      target: polarismesh://trpc.study.HelloWorld
      network: tcp
      protocol: trpc
      timeout: 1200
```

The demo server launched an client invoking itself, but all failed.

---

Secondly, which parameter in polaris mesh page is `token`?
In internal system, this is clear, each server has its own token. 
but the open version, what i see are only "revision" for each server:

![image](https://github.com/trpc-ecosystem/go-naming-polarismesh/assets/6083108/92ca6e0b-2ec4-442d-b206-491bc4a75181)

and the token for each account:

![image](https://github.com/trpc-ecosystem/go-naming-polarismesh/assets/6083108/e6adb0f7-7f72-47cd-89c2-bf5115bae797)

**Comment by tocrafty** [comment]
1. For `host should not be empty` error, you should add `yaml.server.service[0].ip = 127.0.0.1`.
2. It seems that token is not used by polaris server. Any string but empty is accepted as I tested. I will create a PR to remove the strict non-empty string requirment.

**Comment by Andrew-M-C** [comment]
> 1. For `host should not be empty` error, you should add `yaml.server.service[0].ip = 127.0.0.1`.
> 2. It seems that token is not used by polaris server. Any string but empty is accepted as I tested. I will create a PR to remove the strict non-empty string requirment.

@tocrafty I added `nic` and ran again, but now failed in registering:

`trpc_go.yaml`

```yaml
global:
  namespace: dev

server:
  filter:
    - tracelog
  service:
    - name: trpc.study.HelloWorld
      nic: eth0
      # ip: 127.0.0.1
      port: 8000
      network: tcp
      protocol: trpc
      timeout: 1800

plugins:
  log:
    default:
      blahblah... (unchanged)

  registry:
    polarismesh:
      register_self: true
      heartbeat_interval: 3000
      protocol: grpc
      address_list: host.docker.internal:8090
      service:
        - name: trpc.study.HelloWorld
          namespace: dev
          bind_address: host.docker.internal:8000
          weight: 100
          token: not_needed
  selector:
    polarismesh:
      protocol: grpc
      address_list: host.docker.internal:8090

client:
  filter:
    - tracelog
  service:
    - name: trpc.study.HelloWorld
      target: polarismesh://trpc.study.HelloWorld
      network: tcp
      protocol: trpc
      timeout: 1200
```

But I got another error log:

```
2023-11-28 01:44:54.398 ERROR   server/service.go:162   process:398, service:trpc.study.HelloWorld register fail:fail to Register instance, err is Polaris-1004(ErrCodeAPITimeoutError): fail to do register after retry 1 times, cause: Polaris-1007(ErrCodeNetworkError): fail to get connection, opKey RegisterInstance, cause: fail to connect to host.docker.internal:8090, timeout is 1.000451364s, service is {ServiceKey: {namespace: "Polaris", service: "polaris-default"}, ClusterType: builtin}, because context deadline exceeded
2023-11-28 01:44:54.701 INFO    admin/admin.go:192      process:398, admin server, closed
2023-11-28 01:44:54.702 ERROR   server/serve_unix.go:82 service serve errors: 1 error occurred:
        * fail to Register instance, err is Polaris-1004(ErrCodeAPITimeoutError): fail to do register after retry 1 times, cause: Polaris-1007(ErrCodeNetworkError): fail to get connection, opKey RegisterInstance, cause: fail to connect to host.docker.internal:8090, timeout is 1.000451364s, service is {ServiceKey: {namespace: "Polaris", service: "polaris-default"}, ClusterType: builtin}, because context deadline exceeded


Note: it is normal to have "use of closed network connection" error during hot restart.
DO NOT panic.
```

But `host.docker.internal:8090` is ok in docker:

```shell
# curl host.docker.internal:8090
Polaris Server
```

Anything I should do?

**Comment by tocrafty** [comment]
Your address_list should be **service-grpc**, not **api-http**. If you are using **polaris-standalone-release_vx.y.z.docker-compose.zip**, the port of service-grpc should be 8091.

**Comment by Andrew-M-C** [comment]
@tocrafty Thanks a lot!! I changed 8090 to 8091，it worked!
